name: rda
favicon: null
layout_spectrum: 0.374126193812117
typography_spectrum: 0.325196128571406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3744139450136572
  lightness: 0.6099515412934124
  saturation: 0.3135498226620257
  rhythmicContrast: 0.2506895607803017
purpose: []
